### ISSUE TITLE
[VanishNoPacket] Error On Startup

### ISSUE THREAD

**Issue by venatha** [keepcalm/BukkitForge#330]
VanishNoPaket http://dev.bukkit.org/server-mods/vanish/files/57-v3-12-1/ crash on startup using  BukkitForge-1.4.7-89 and plugin version v3.12.1

Error Attached : http://pastebin.com/5pQCD5sE

**Comment by SpoonsJTD** [comment]
This plugin references a base class (that I don't think even exists, at least not in the package referenced) and is developed against CB 1.3.2-R1.0, which was before the big 1.4 update, so isn't going to work. Have the plug-in author update to 1.4x.

**Comment by venatha** [comment]
My bad, i was testing a older version, newer version against the right craftbukkit version throws http://pastebin.com/3vZQt59w

**Comment by SpoonsJTD** [comment]
Re-opening since verified on latest version.

**Comment by SpoonsJTD** [comment]
Performs its own version check. If configurable, please disable it. If not, contact the plugin author and ask to make it configurable.

**Comment by agaricusb** [comment]
@SpoonsJTD not exactly a version "check"; VanishNoPacket is trying to determine the correct "NMS handler" to load https://github.com/mbax/VanishNoPacket/blob/master/src/main/java/org/kitteh/vanish/compat/NMSManager.java:

> ```
>     final String packageName = plugin.getServer().getClass().getPackage().getName();
> ```

but its falling back to 1.4.5 because its finding org.bukkit.craftbukkit instead of org.bukkit.craftbukkit.v1_4_R1 (as in vanilla CraftBukkit 1.4.7)
