### ISSUE TITLE
[Pex] Still Having problems

### ISSUE THREAD

**Issue by Talenemrys** [keepcalm/BukkitForge#339]
Howdy, I've been trying for a few days to get PEX to work with BukkitForge, and I've gotten very close, but it seems that the Modifyworld node isn't doing anything.. Nobody can do anything while pex is active, and my permissions is as follows:

groups:
  default:
    default: true
    permissions:
    - modifyworld.*
(They are tabulated correctly in the file, this seems to remove the spaces)
I'm using the latest Bukkitforge (1.4.7-91, posted 2 hours ago, or thereabouts), and I've tried using both versions of pex linked to on the  Minecraft Forums page (http://files.electro-gaming.org/BukkitForge/), and it's loading fine, no problems highlighted in the console, no error logs cropping up, it just refuses to actually give permissions.

Any ideas?
Cheers in advance,
Talen

**Comment by BubblyLemon** [comment]
I suggest using groupmanager which is very similiar in functionality when paired with essentialsprotect and worldguard for example.

I don't think PEX is working for anyone right now, however groupmanager is working as far as I can tell close to 100% for me (haven't tested everything)

**Comment by Talenemrys** [comment]
Hmm, I have a pex config file already set up, and from what I can see on here they've closed all the other PEX problems saying that it's fixed.. But it's not! xD
I'll give groupmanager a go later though, if I can't find a fix for PEX

**Comment by SpoonsJTD** [comment]
Pex doesn't work. Bperms, superperms, and other perm plugins work I believe.

**Comment by Talenemrys** [comment]
Ah, alright then =/
I'll see if any of them have the same/similar format for the file, I do have a huge permissions file set up for Pex :/

Thanks anyways

**Comment by SpoonsJTD** [comment]
Re-opening, Pex does need to be fixed. I believe keepcalm is working on it.

**Comment by Listy** [comment]
Spoons,  could I just ask what problems Pex currently has?  I ask because I've seen some people report that it doesn't work at all (the problem I seem to be having) but I also hear some people say that they've almost got it working and only reporting problems it has with particular permissions nodes.

I'm using build 109, the 2nd version of the ported pex file linked to off here, and worldguard/worldedit - if i take myself out of the op text file I can break/place blocks etc.... but no plugin permissions in worldedit for instance.   I'm using my old pex permissions file that I know worked (but maybe that's the issue if the ported pex here formats it's files slightly different...i don't know if that's the case).

I just want to make sure i'm following the right issue so I know if my problem is something i've done stupid...or if it's the same one everyone is having and I can sit back down and patiently wait for a fix,  Also if some people have indeed got most of it working already then I can aim for that now.

Thanks

**Comment by Tampa** [comment]
Build 112 did not fix the issue.

**Comment by keepcalm** [comment]
Which permissions are you using to test this? Essentials has some config options which conflict with Modifyworld.

**Comment by Tampa** [comment]
Pex, trying to op myself with bukkit.*, but it doesn'T work. Only /stop seems to work.

**Comment by Listy** [comment]
Hi Keepcalm,  I'm not using essentials at all

My setup is as follows

build 126
worldedit
worldguard
unlimitedlava (a plugin I've used previously on other servers to test if it works...it doesn't)
the ported version of PeX (2nd version off your link) - with permissions file that works on another server of mine running tekkit with PeX.

When the server starts it appears to load PeX properly and doesn't throw out any error messages but when I test commands such as 

//wand
/time set 0
try to change gamemode
or even try to take a bucket of lava with unlimitedlava loaded

I get the 'you do not have permmisions to do this' message.

**Comment by Listy** [comment]
A quick update 

by adding the '*' wildcard permission to the user section in the permissions.yml file I can now run some basic PeX commands - but it doesn't give me all permissions like the wildcard should e.g.  setting gamemode, time of day, etc.

but at least now I can run the PeX users command to list what PeX thinks my groups are for the world and the results surprised me a little because PeX sees all my users as in the correct groups (I was beginning to think it wasn't reading the permissions file at all) - it's just not applying the appropriate permissions for each group or user.

but as I said, at least it shows that the file is being read in, it is parsing the users/groups ok.... just the applying permissions bit seems awry.

**Comment by Listy** [comment]
Further update:   I just read your document on PEX/PEX developer issues and have decided to now move away from using it as my permissions plugin.

I have a huge PEX permissions file one one of my production servers so I was hoping to avoid re-doing all that work again...but hey ho, if it needs doing it needs doing.

Thanks for writing that document (didn't want to link to it off here in case you didn't want that), it explained a lot of issues I've had in the past with PEX that I've just been living  with .

**Comment by Tampa** [comment]
How far down the priority list is this, i feel like everyone reporting Pex issues either is missing something or it's really not working and no one cares.

**Comment by keepcalm** [comment]
Go onto #bukkitforge on irc.esper.net and type |pex2gm. Instructions on how to switch are there. We can't support PEX as it keeps breaking.

**Comment by Mastergalen** [comment]
:/ That is quite a shame, since PEX is the only stable Permissions plugin which supports MySQL. All of the automatic application promotion system on my server relies on PEX functioning. 

Also allowed me to have permissions to persist between servers.
