### ISSUE TITLE
[Permissions] Update from build 91 to 95

### ISSUE THREAD

**Issue by gpremier** [keepcalm/BukkitForge#356]
Hey there, I just update BukkitForge from build 91 to build 95 and now PermissionsEx not working anymore.

PermissionsEx get loaded 
"23.01 22:52:34 [Server] INFO [BukkitForge] PermissionsEx- Enabled: true"
and I haven't any crash report for you but permissions won't work anymore.
I tested build 94 and I got the same problem.

I would like to return to build 91 but I can't get it anymore on Jenkins...

Thank you in advance and have a nice day.

**Comment by krim404** [comment]
Confirmed - same problem here.

**Comment by Tampa** [comment]
Build 91 is also bugged. It seems only bukkit permissions do not work, pex itself is working, same for modifyworld and chatmanager(although that doesn't display prefixes).
Btw, in order to test earlier builds could you either configure the jenkins to upload each build externally, id give you an ftp location if you need one, or tell the jenkins not to delete them?

**Comment by krim404** [comment]
OP problem should be fixed now.
