### ISSUE TITLE
PermisionsEX not working

### ISSUE THREAD

**Issue by tacoriffic926** [keepcalm/BukkitForge#397]
I am running the latest build 151 and downloaded the newest pexs from http://files.electro-gaming.org/BukkitForge/ but i keep getting

2013-01-28 16:30:11 [WARNING] [PermissionsEx] Unknown server implementation being used!

and i can't build in towny wilderness when i use BukkitForge build 126 it works

**Comment by keepcalm** [comment]
Unfortunately, we can't support PEX, simply because it's too bulky and hackish

If you use PEX you can use http://pex2gm.cgw.me/ to convert your permissions file and http://gravypod.com:8111/viewLog.html?buildId=lastSuccessful&buildTypeId=bt14&tab=artifacts&guest=1 to replace ModifyWorld. We recommend GroupManager over any other (PermissionsEx in particular) permissions plugins. For a list of reasons why, please read http://bit.ly/QBTtcQ
