### ISSUE TITLE
LWC or an alternative?

### ISSUE THREAD

**Issue by ghost** [keepcalm/BukkitForge#470]
Does LWC working for anyone or does anybody know an alternative for this bukkit plugin, who can lock chests (and works for BukkitForge).
I hope you can help me!

**Comment by EDSman11** [comment]
Lockette works... I would go with SecureChests if u need a command based
locking system

**Comment by fhntv24** [comment]
yea it's working.and you can go with mod,wich add that too :)(copygirl chest mod)

**Comment by ghost** [comment]
but there's everytime an "PLAYER_INTERACT" error :(

**Comment by BubblyLemon** [comment]
Every placement of a chest issues a "PLAYER_INTERACT" error to the player, and then this to the console.

8:30:18 PM
 CONSOLE:
[INFO] com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 4.3.1 (b767)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:358)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.listeners.LWCBlockListener.onBlockPlace(LWCBlockListener.java:375)
8:30:18 PM
 CONSOLE:
[INFO] at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
8:30:18 PM
 CONSOLE:
[INFO] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
8:30:18 PM
 CONSOLE:
[INFO] at java.lang.reflect.Method.invoke(Unknown Source)
8:30:18 PM
 CONSOLE:
[INFO] at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:391)
8:30:18 PM
 CONSOLE:
[INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
8:30:18 PM
 CONSOLE:
[INFO] at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482)
8:30:18 PM
 CONSOLE:
[INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:464)
8:30:18 PM
 CONSOLE:
[INFO] at keepcalm.mods.bukkit.forgeHandler.ForgeEventHandler.onPlayerInteraction(ForgeEventHandler.java:375)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraftforge.event.ASMEventHandler_121_ForgeEventHandler_onPlayerInteraction_PlayerInteractEvent.invoke(.dynamic)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraftforge.event.ASMEventHandler.invoke(ASMEventHandler.java:35)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraftforge.event.EventBus.post(EventBus.java:103)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:34)
8:30:18 PM
 CONSOLE:
[INFO] at ir.a(ItemInWorldManager.java:389)
8:30:18 PM
 CONSOLE:
[INFO] at iv.a(NetServerHandler.java:578)
8:30:18 PM
 CONSOLE:
[INFO] at fk.a(SourceFile:58)
8:30:18 PM
 CONSOLE:
[INFO] at cg.b(TcpConnection.java:458)
8:30:18 PM
 CONSOLE:
[INFO] at iv.d(NetServerHandler.java:136)
8:30:18 PM
 CONSOLE:
[INFO] at iw.b(NetworkListenThread.java:57)
8:30:18 PM
 CONSOLE:
[INFO] at ht.b(SourceFile:30)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:703)
8:30:18 PM
 CONSOLE:
[INFO] at ho.r(DedicatedServer.java:269)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:599)
8:30:18 PM
 CONSOLE:
[INFO] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
8:30:18 PM
 CONSOLE:
[INFO] at fy.run(SourceFile:849)
8:30:18 PM
 CONSOLE:
[INFO] Caused by: java.lang.NullPointerException
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.sql.PhysDB.getProtectionCount(PhysDB.java:165)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.modules.limits.LimitsV2$DefaultLimit.getProtectionCount(LimitsV2.java:112)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.modules.limits.LimitsV2.hasReachedLimit(LimitsV2.java:286)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.modules.limits.LimitsV2.onRegisterProtection(LimitsV2.java:162)
8:30:18 PM
 CONSOLE:
[INFO] at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:346)
8:30:18 PM
 CONSOLE:
[INFO] ... 25 more

**Comment by BushTrocity** [comment]
http://forums.bukkit.org/threads/sec-mech-simplechestlock-1-2-1-simplified-chest-locking-1-4-6r0-3.17557/

That chest locking plugin works fine if u just want to lock chests. I haven't had any problems with it even added custom lockable ids. Only gives a small error sometimes but it still works. World Edit works. I can fix water and do anything else even import and save schematics. I haven't had any problems with world edit. I'm using essentials also. Vanish works, it gives u an invisibility potion but the block in your had and gear is visible. Also lift click with the compass doesn't work unless you are in within 3 block of where u want to go. The /jumpto command works fine you just face the wrong way lol. The /spawn command works, /sethome works, /home works, /back is still a little bugging. And don't use it if u in a different world i learned the hard way lol. I'm using chest shop too and i haven't had any problems with it either sometimes the items you buy doesn't show in your inventory but it is there just a bug re-log or click on it to make it show up.

Using bukkitforge - 139
Tekkit lite running - 1.4.7

**Comment by fhntv24** [comment]
heh and i just remembered-on MCPC+ topic there is LWC for MPCP+ wich fix that problem
