### ISSUE TITLE
Build 12 error

### ISSUE THREAD

**Issue by xKillerbees** [keepcalm/BukkitForge#52]
29.12 00:20:25 [Server] INFO at fy.run(SourceFile:849)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
29.12 00:20:25 [Server] INFO at ho.r(DedicatedServer.java:270)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
29.12 00:20:25 [Server] INFO at ht.b(SourceFile:29)
29.12 00:20:25 [Server] INFO at hu.a(ServerListenThread.java:56)
29.12 00:20:25 [Server] INFO at it.c(NetLoginHandler.java:72)
29.12 00:20:25 [Server] INFO at it.d(NetLoginHandler.java:179)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:133)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.connectionReceived(NetworkRegistry.java:169)
29.12 00:20:25 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.connectionReceived(ConnectionHandler.java:66)
29.12 00:20:25 [Server] INFO at org.bukkit.Bukkit.getPluginManager(Bukkit.java:140)
29.12 00:20:25 [Server] INFO java.lang.NullPointerException
29.12 00:20:25 [Server] WARNING Failed to handle packet for xKillerbees []: java.lang.NullPointerException
29.12 00:20:25 [Server] INFO at fy.run(SourceFile:849)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:497)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:598)
29.12 00:20:25 [Server] INFO at ho.r(DedicatedServer.java:270)
29.12 00:20:25 [Server] INFO at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:702)
29.12 00:20:25 [Server] INFO at ht.b(SourceFile:29)
29.12 00:20:25 [Server] INFO at hu.a(ServerListenThread.java:56)
29.12 00:20:25 [Server] INFO at it.c(NetLoginHandler.java:72)
29.12 00:20:25 [Server] INFO at it.d(NetLoginHandler.java:179)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.onConnectionReceivedFromClient(FMLNetworkHandler.java:107)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.FMLNetworkHandler.handleClientConnection(FMLNetworkHandler.java:133)
29.12 00:20:25 [Server] INFO at cpw.mods.fml.common.network.NetworkRegistry.connectionReceived(NetworkRegistry.java:169)
29.12 00:20:25 [Server] INFO at keepcalm.mods.bukkit.forgeHandler.ConnectionHandler.connectionReceived(ConnectionHandler.java:66)
29.12 00:20:25 [Server] INFO at org.bukkit.Bukkit.getPluginManager(Bukkit.java:140)
29.12 00:20:25 [Server] INFO java.lang.NullPointerException
29.12 00:20:25 [Server] SEVERE Error handling login related packet - connection from xKillerbees [/] refused
29.12 00:20:25 [Server] INFO Disconnecting xKillerbees [/]: Internal server error

29.12 00:17:14 [Server] INFO    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
29.12 00:17:14 [Server] INFO    at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
29.12 00:17:14 [Server] INFO    at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:38)
29.12 00:17:14 [Server] INFO Caused by: java.lang.RuntimeException: Attempted to load class bdz for invalid side SERVER
29.12 00:17:14 [Server] INFO    ... 2 more
29.12 00:17:14 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
29.12 00:17:14 [Server] INFO    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
29.12 00:17:14 [Server] INFO    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
29.12 00:17:14 [Server] INFO Caused by: java.lang.ClassNotFoundException: bdz
29.12 00:17:14 [Server] INFO    at java.lang.Thread.run(Thread.java:722)
29.12 00:17:14 [Server] INFO    at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
29.12 00:17:14 [Server] INFO Exception in thread "BukkitCoreAPI-0" java.lang.NoClassDefFoundError: bdz

**Comment by keepcalm** [comment]
Whoops. Sorry. I start fixing towny, something else breaks...

**Comment by Tampa** [comment]
2012-12-29 18:39:20 [INFO] [STDERR] Exception in thread "BukkitCoreAPI-0" java.lang.NoClassDefFoundError: bdz
2012-12-29 18:39:20 [INFO] [STDERR]     at keepcalm.mods.bukkit.asm.BukkitStarter.run(BukkitStarter.java:38)
2012-12-29 18:39:20 [INFO] [STDERR]     at java.lang.Thread.run(Thread.java:722)
2012-12-29 18:39:20 [INFO] [STDERR] Caused by: java.lang.ClassNotFoundException: bdz
2012-12-29 18:39:20 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:179)
2012-12-29 18:39:20 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
2012-12-29 18:39:20 [INFO] [STDERR]     at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
2012-12-29 18:39:20 [INFO] [STDERR]     ... 2 more
2012-12-29 18:39:20 [INFO] [STDERR] Caused by: java.lang.RuntimeException: Attempted to load class bdz for invalid side SERVER
2012-12-29 18:39:20 [INFO] [STDERR]     at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:38)
2012-12-29 18:39:20 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.runTransformers(RelaunchClassLoader.java:222)
2012-12-29 18:39:20 [INFO] [STDERR]     at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:171)
2012-12-29 18:39:20 [INFO] [STDERR]     ... 4 more
2012-12-29 18:39:21 [INFO] [STDOUT] Loading NEI

It asks for bdz, so give it that maybe?

**Comment by keepcalm** [comment]
Ah... It shouldn't ask for bdz. bdz is Client-side only
